/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.repo.api.impl.jooq.entity.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.oagi.score.repo.api.impl.jooq.entity.tables.BieGapAnalysisStatusCode;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BieGapAnalysisStatusCodeRecord extends UpdatableRecordImpl<BieGapAnalysisStatusCodeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>oagi.bie_gap_analysis_status_code.status_id</code>.
     */
    public void setStatusId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>oagi.bie_gap_analysis_status_code.status_id</code>.
     */
    public Long getStatusId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>oagi.bie_gap_analysis_status_code.code</code>.
     */
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>oagi.bie_gap_analysis_status_code.code</code>.
     */
    public String getCode() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BieGapAnalysisStatusCodeRecord
     */
    public BieGapAnalysisStatusCodeRecord() {
        super(BieGapAnalysisStatusCode.BIE_GAP_ANALYSIS_STATUS_CODE);
    }

    /**
     * Create a detached, initialised BieGapAnalysisStatusCodeRecord
     */
    public BieGapAnalysisStatusCodeRecord(Long statusId, String code) {
        super(BieGapAnalysisStatusCode.BIE_GAP_ANALYSIS_STATUS_CODE);

        setStatusId(statusId);
        setCode(code);
        resetChangedOnNotNull();
    }
}
