/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.repo.api.impl.jooq.entity.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.oagi.score.repo.api.impl.jooq.entity.tables.BieGapAnalysis;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BieGapAnalysisRecord extends UpdatableRecordImpl<BieGapAnalysisRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>oagi.bie_gap_analysis.gap_analysis_id</code>.
     */
    public void setGapAnalysisId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>oagi.bie_gap_analysis.gap_analysis_id</code>.
     */
    public Long getGapAnalysisId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>oagi.bie_gap_analysis.source_top_level_asbiep_id</code>.
     */
    public void setSourceTopLevelAsbiepId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>oagi.bie_gap_analysis.source_top_level_asbiep_id</code>.
     */
    public Long getSourceTopLevelAsbiepId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>oagi.bie_gap_analysis.target_top_level_asbiep_id</code>.
     */
    public void setTargetTopLevelAsbiepId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>oagi.bie_gap_analysis.target_top_level_asbiep_id</code>.
     */
    public Long getTargetTopLevelAsbiepId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached BieGapAnalysisRecord
     */
    public BieGapAnalysisRecord() {
        super(BieGapAnalysis.BIE_GAP_ANALYSIS);
    }

    /**
     * Create a detached, initialised BieGapAnalysisRecord
     */
    public BieGapAnalysisRecord(Long gapAnalysisId, Long sourceTopLevelAsbiepId, Long targetTopLevelAsbiepId) {
        super(BieGapAnalysis.BIE_GAP_ANALYSIS);

        setGapAnalysisId(gapAnalysisId);
        setSourceTopLevelAsbiepId(sourceTopLevelAsbiepId);
        setTargetTopLevelAsbiepId(targetTopLevelAsbiepId);
        resetChangedOnNotNull();
    }
}
