/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.repo.api.impl.jooq.entity.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.oagi.score.repo.api.impl.jooq.entity.tables.CcGapAnalysisResultCode;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CcGapAnalysisResultCodeRecord extends UpdatableRecordImpl<CcGapAnalysisResultCodeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>oagi.cc_gap_analysis_result_code.code_id</code>.
     */
    public void setCodeId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>oagi.cc_gap_analysis_result_code.code_id</code>.
     */
    public Long getCodeId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>oagi.cc_gap_analysis_result_code.code</code>.
     */
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>oagi.cc_gap_analysis_result_code.code</code>.
     */
    public String getCode() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CcGapAnalysisResultCodeRecord
     */
    public CcGapAnalysisResultCodeRecord() {
        super(CcGapAnalysisResultCode.CC_GAP_ANALYSIS_RESULT_CODE);
    }

    /**
     * Create a detached, initialised CcGapAnalysisResultCodeRecord
     */
    public CcGapAnalysisResultCodeRecord(Long codeId, String code) {
        super(CcGapAnalysisResultCode.CC_GAP_ANALYSIS_RESULT_CODE);

        setCodeId(codeId);
        setCode(code);
        resetChangedOnNotNull();
    }
}
