/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.repo.api.impl.jooq.entity.tables.records;


import org.jooq.impl.TableRecordImpl;
import org.jooq.types.ULong;
import org.oagi.score.repo.api.impl.jooq.entity.tables.FlatBccView;


/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FlatBccViewRecord extends TableRecordImpl<FlatBccViewRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>oagi.flat_bcc_view.object_class_term</code>. Object
     * class name of the ACC concept. For OAGIS, this is generally name of a
     * type with the "Type" truncated from the end. Per CCS the name is space
     * separated. "ID" is expanded to "Identifier".
     */
    public void setObjectClassTerm(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>oagi.flat_bcc_view.object_class_term</code>. Object
     * class name of the ACC concept. For OAGIS, this is generally name of a
     * type with the "Type" truncated from the end. Per CCS the name is space
     * separated. "ID" is expanded to "Identifier".
     */
    public String getObjectClassTerm() {
        return (String) get(0);
    }

    /**
     * Setter for <code>oagi.flat_bcc_view.bcc_id</code>. A internal, primary
     * database key of an BCC.
     */
    public void setBccId(ULong value) {
        set(1, value);
    }

    /**
     * Getter for <code>oagi.flat_bcc_view.bcc_id</code>. A internal, primary
     * database key of an BCC.
     */
    public ULong getBccId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>oagi.flat_bcc_view.dt_sc_id</code>. Internal, primary
     * database key.
     */
    public void setDtScId(ULong value) {
        set(2, value);
    }

    /**
     * Getter for <code>oagi.flat_bcc_view.dt_sc_id</code>. Internal, primary
     * database key.
     */
    public ULong getDtScId() {
        return (ULong) get(2);
    }

    /**
     * Setter for <code>oagi.flat_bcc_view.property_term</code>. The property
     * concept that the BCCP models.
     */
    public void setPropertyTerm(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>oagi.flat_bcc_view.property_term</code>. The property
     * concept that the BCCP models.
     */
    public String getPropertyTerm() {
        return (String) get(3);
    }

    /**
     * Setter for <code>oagi.flat_bcc_view.dt_sc_den</code>.
     */
    public void setDtScDen(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>oagi.flat_bcc_view.dt_sc_den</code>.
     */
    public String getDtScDen() {
        return (String) get(4);
    }

    /**
     * Setter for <code>oagi.flat_bcc_view.super_bcc_id</code>.
     */
    public void setSuperBccId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>oagi.flat_bcc_view.super_bcc_id</code>.
     */
    public Long getSuperBccId() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FlatBccViewRecord
     */
    public FlatBccViewRecord() {
        super(FlatBccView.FLAT_BCC_VIEW);
    }

    /**
     * Create a detached, initialised FlatBccViewRecord
     */
    public FlatBccViewRecord(String objectClassTerm, ULong bccId, ULong dtScId, String propertyTerm, String dtScDen, Long superBccId) {
        super(FlatBccView.FLAT_BCC_VIEW);

        setObjectClassTerm(objectClassTerm);
        setBccId(bccId);
        setDtScId(dtScId);
        setPropertyTerm(propertyTerm);
        setDtScDen(dtScDen);
        setSuperBccId(superBccId);
        resetChangedOnNotNull();
    }
}
