/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.repo.api.impl.jooq.entity.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;
import org.oagi.score.repo.api.impl.jooq.entity.tables.FlatBcc;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FlatBccRecord extends UpdatableRecordImpl<FlatBccRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>oagi.flat_bcc.flat_bcc_id</code>.
     */
    public void setFlatBccId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>oagi.flat_bcc.flat_bcc_id</code>.
     */
    public Long getFlatBccId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>oagi.flat_bcc.acc_id</code>.
     */
    public void setAccId(ULong value) {
        set(1, value);
    }

    /**
     * Getter for <code>oagi.flat_bcc.acc_id</code>.
     */
    public ULong getAccId() {
        return (ULong) get(1);
    }

    /**
     * Setter for <code>oagi.flat_bcc.bcc_id</code>.
     */
    public void setBccId(ULong value) {
        set(2, value);
    }

    /**
     * Getter for <code>oagi.flat_bcc.bcc_id</code>.
     */
    public ULong getBccId() {
        return (ULong) get(2);
    }

    /**
     * Setter for <code>oagi.flat_bcc.dt_sc_id</code>.
     */
    public void setDtScId(ULong value) {
        set(3, value);
    }

    /**
     * Getter for <code>oagi.flat_bcc.dt_sc_id</code>.
     */
    public ULong getDtScId() {
        return (ULong) get(3);
    }

    /**
     * Setter for <code>oagi.flat_bcc.super_bcc_id</code>.
     */
    public void setSuperBccId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>oagi.flat_bcc.super_bcc_id</code>.
     */
    public Long getSuperBccId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>oagi.flat_bcc.Path</code>.
     */
    public void setPath(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>oagi.flat_bcc.Path</code>.
     */
    public String getPath() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FlatBccRecord
     */
    public FlatBccRecord() {
        super(FlatBcc.FLAT_BCC);
    }

    /**
     * Create a detached, initialised FlatBccRecord
     */
    public FlatBccRecord(Long flatBccId, ULong accId, ULong bccId, ULong dtScId, Long superBccId, String path) {
        super(FlatBcc.FLAT_BCC);

        setFlatBccId(flatBccId);
        setAccId(accId);
        setBccId(bccId);
        setDtScId(dtScId);
        setSuperBccId(superBccId);
        setPath(path);
        resetChangedOnNotNull();
    }
}
