/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.repo.api.impl.jooq.entity.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.oagi.score.repo.api.impl.jooq.entity.tables.FlatBcc;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FlatBccRecord extends UpdatableRecordImpl<FlatBccRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>oagi.flat_bcc.flat_bcc_id</code>.
     */
    public void setFlatBccId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>oagi.flat_bcc.flat_bcc_id</code>.
     */
    public Long getFlatBccId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>oagi.flat_bcc.acc_id</code>.
     */
    public void setAccId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>oagi.flat_bcc.acc_id</code>.
     */
    public Long getAccId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>oagi.flat_bcc.bcc_id</code>.
     */
    public void setBccId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>oagi.flat_bcc.bcc_id</code>.
     */
    public Long getBccId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>oagi.flat_bcc.dt_sc_id</code>.
     */
    public void setDtScId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>oagi.flat_bcc.dt_sc_id</code>.
     */
    public Long getDtScId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>oagi.flat_bcc.super_bcc_id</code>.
     */
    public void setSuperBccId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>oagi.flat_bcc.super_bcc_id</code>.
     */
    public Long getSuperBccId() {
        return (Long) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FlatBccRecord
     */
    public FlatBccRecord() {
        super(FlatBcc.FLAT_BCC);
    }

    /**
     * Create a detached, initialised FlatBccRecord
     */
    public FlatBccRecord(Long flatBccId, Long accId, Long bccId, Long dtScId, Long superBccId) {
        super(FlatBcc.FLAT_BCC);

        setFlatBccId(flatBccId);
        setAccId(accId);
        setBccId(bccId);
        setDtScId(dtScId);
        setSuperBccId(superBccId);
        resetChangedOnNotNull();
    }
}
