/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.repo.api.impl.jooq.entity.tables.records;


import org.jooq.impl.TableRecordImpl;
import org.oagi.score.repo.api.impl.jooq.entity.tables.FlatBccView_2;


/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FlatBccView_2Record extends TableRecordImpl<FlatBccView_2Record> {

    private static final long serialVersionUID = 1L;

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached FlatBccView_2Record
     */
    public FlatBccView_2Record() {
        super(FlatBccView_2.FLAT_BCC_VIEW_2);
    }
}
