/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.repo.api.impl.jooq.entity.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.oagi.score.repo.api.impl.jooq.entity.tables.MappingSpecification;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MappingSpecificationRecord extends UpdatableRecordImpl<MappingSpecificationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>oagi.mapping_specification.mapping_specification_id</code>.
     */
    public void setMappingSpecificationId(Long value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>oagi.mapping_specification.mapping_specification_id</code>.
     */
    public Long getMappingSpecificationId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>oagi.mapping_specification.mapping_specification</code>.
     */
    public void setMappingSpecification(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>oagi.mapping_specification.mapping_specification</code>.
     */
    public String getMappingSpecification() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MappingSpecificationRecord
     */
    public MappingSpecificationRecord() {
        super(MappingSpecification.MAPPING_SPECIFICATION);
    }

    /**
     * Create a detached, initialised MappingSpecificationRecord
     */
    public MappingSpecificationRecord(Long mappingSpecificationId, String mappingSpecification) {
        super(MappingSpecification.MAPPING_SPECIFICATION);

        setMappingSpecificationId(mappingSpecificationId);
        setMappingSpecification(mappingSpecification);
        resetChangedOnNotNull();
    }
}
