/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.repo.api.impl.jooq.entity.tables.records;


import org.jooq.impl.TableRecordImpl;
import org.oagi.score.repo.api.impl.jooq.entity.tables.MatchingCc;


/**
 * VIEW
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MatchingCcRecord extends TableRecordImpl<MatchingCcRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>oagi.matching_cc.source_spec</code>.
     */
    public void setSourceSpec(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>oagi.matching_cc.source_spec</code>.
     */
    public String getSourceSpec() {
        return (String) get(0);
    }

    /**
     * Setter for <code>oagi.matching_cc.target_spec</code>.
     */
    public void setTargetSpec(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>oagi.matching_cc.target_spec</code>.
     */
    public String getTargetSpec() {
        return (String) get(1);
    }

    /**
     * Setter for <code>oagi.matching_cc.super_bcc_id</code>.
     */
    public void setSuperBccId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>oagi.matching_cc.super_bcc_id</code>.
     */
    public Long getSuperBccId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MatchingCcRecord
     */
    public MatchingCcRecord() {
        super(MatchingCc.MATCHING_CC);
    }

    /**
     * Create a detached, initialised MatchingCcRecord
     */
    public MatchingCcRecord(String sourceSpec, String targetSpec, Long superBccId) {
        super(MatchingCc.MATCHING_CC);

        setSourceSpec(sourceSpec);
        setTargetSpec(targetSpec);
        setSuperBccId(superBccId);
        resetChangedOnNotNull();
    }
}
