/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.repo.api.impl.jooq.entity.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.oagi.score.repo.api.impl.jooq.entity.tables.Source;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SourceRecord extends UpdatableRecordImpl<SourceRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>oagi.source.source_id</code>.
     */
    public void setSourceId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>oagi.source.source_id</code>.
     */
    public Long getSourceId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>oagi.source.source_name</code>.
     */
    public void setSourceName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>oagi.source.source_name</code>.
     */
    public String getSourceName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SourceRecord
     */
    public SourceRecord() {
        super(Source.SOURCE);
    }

    /**
     * Create a detached, initialised SourceRecord
     */
    public SourceRecord(Long sourceId, String sourceName) {
        super(Source.SOURCE);

        setSourceId(sourceId);
        setSourceName(sourceName);
        resetChangedOnNotNull();
    }
}
