/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.repo.api.impl.jooq.entity.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.oagi.score.repo.api.impl.jooq.entity.tables.SpecificationDataTypeAttribute;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpecificationDataTypeAttributeRecord extends UpdatableRecordImpl<SpecificationDataTypeAttributeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>oagi.specification_data_type_attribute.dt_attribute_id</code>.
     */
    public void setDtAttributeId(Long value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>oagi.specification_data_type_attribute.dt_attribute_id</code>.
     */
    public Long getDtAttributeId() {
        return (Long) get(0);
    }

    /**
     * Setter for
     * <code>oagi.specification_data_type_attribute.dt_attribute_name</code>.
     */
    public void setDtAttributeName(String value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>oagi.specification_data_type_attribute.dt_attribute_name</code>.
     */
    public String getDtAttributeName() {
        return (String) get(1);
    }

    /**
     * Setter for
     * <code>oagi.specification_data_type_attribute.definition</code>.
     */
    public void setDefinition(String value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>oagi.specification_data_type_attribute.definition</code>.
     */
    public String getDefinition() {
        return (String) get(2);
    }

    /**
     * Setter for
     * <code>oagi.specification_data_type_attribute.min_cardinality</code>.
     */
    public void setMinCardinality(Integer value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>oagi.specification_data_type_attribute.min_cardinality</code>.
     */
    public Integer getMinCardinality() {
        return (Integer) get(3);
    }

    /**
     * Setter for
     * <code>oagi.specification_data_type_attribute.max_cardinality</code>.
     */
    public void setMaxCardinality(Integer value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>oagi.specification_data_type_attribute.max_cardinality</code>.
     */
    public Integer getMaxCardinality() {
        return (Integer) get(4);
    }

    /**
     * Setter for
     * <code>oagi.specification_data_type_attribute.from_data_type_id</code>.
     */
    public void setFromDataTypeId(Long value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>oagi.specification_data_type_attribute.from_data_type_id</code>.
     */
    public Long getFromDataTypeId() {
        return (Long) get(5);
    }

    /**
     * Setter for
     * <code>oagi.specification_data_type_attribute.to_data_type_id</code>.
     */
    public void setToDataTypeId(Long value) {
        set(6, value);
    }

    /**
     * Getter for
     * <code>oagi.specification_data_type_attribute.to_data_type_id</code>.
     */
    public Long getToDataTypeId() {
        return (Long) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SpecificationDataTypeAttributeRecord
     */
    public SpecificationDataTypeAttributeRecord() {
        super(SpecificationDataTypeAttribute.SPECIFICATION_DATA_TYPE_ATTRIBUTE);
    }

    /**
     * Create a detached, initialised SpecificationDataTypeAttributeRecord
     */
    public SpecificationDataTypeAttributeRecord(Long dtAttributeId, String dtAttributeName, String definition, Integer minCardinality, Integer maxCardinality, Long fromDataTypeId, Long toDataTypeId) {
        super(SpecificationDataTypeAttribute.SPECIFICATION_DATA_TYPE_ATTRIBUTE);

        setDtAttributeId(dtAttributeId);
        setDtAttributeName(dtAttributeName);
        setDefinition(definition);
        setMinCardinality(minCardinality);
        setMaxCardinality(maxCardinality);
        setFromDataTypeId(fromDataTypeId);
        setToDataTypeId(toDataTypeId);
        resetChangedOnNotNull();
    }
}
