/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.repo.api.impl.jooq.entity.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;
import org.oagi.score.repo.api.impl.jooq.entity.tables.SpecificationAggregateComponent;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpecificationAggregateComponentRecord extends UpdatableRecordImpl<SpecificationAggregateComponentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for
     * <code>oagi.specification_aggregate_component.component_id</code>.
     */
    public void setComponentId(Long value) {
        set(0, value);
    }

    /**
     * Getter for
     * <code>oagi.specification_aggregate_component.component_id</code>.
     */
    public Long getComponentId() {
        return (Long) get(0);
    }

    /**
     * Setter for
     * <code>oagi.specification_aggregate_component.definition</code>.
     */
    public void setDefinition(String value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>oagi.specification_aggregate_component.definition</code>.
     */
    public String getDefinition() {
        return (String) get(1);
    }

    /**
     * Setter for
     * <code>oagi.specification_aggregate_component.component_name</code>.
     */
    public void setComponentName(String value) {
        set(2, value);
    }

    /**
     * Getter for
     * <code>oagi.specification_aggregate_component.component_name</code>.
     */
    public String getComponentName() {
        return (String) get(2);
    }

    /**
     * Setter for
     * <code>oagi.specification_aggregate_component.specificationid</code>.
     */
    public void setSpecificationid(Long value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>oagi.specification_aggregate_component.specificationid</code>.
     */
    public Long getSpecificationid() {
        return (Long) get(3);
    }

    /**
     * Setter for
     * <code>oagi.specification_aggregate_component.status_code_id</code>.
     */
    public void setStatusCodeId(Long value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>oagi.specification_aggregate_component.status_code_id</code>.
     */
    public Long getStatusCodeId() {
        return (Long) get(4);
    }

    /**
     * Setter for
     * <code>oagi.specification_aggregate_component.gap_analysis_code_id</code>.
     */
    public void setGapAnalysisCodeId(Long value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>oagi.specification_aggregate_component.gap_analysis_code_id</code>.
     */
    public Long getGapAnalysisCodeId() {
        return (Long) get(5);
    }

    /**
     * Setter for <code>oagi.specification_aggregate_component.acc_id</code>.
     */
    public void setAccId(ULong value) {
        set(6, value);
    }

    /**
     * Getter for <code>oagi.specification_aggregate_component.acc_id</code>.
     */
    public ULong getAccId() {
        return (ULong) get(6);
    }

    /**
     * Setter for
     * <code>oagi.specification_aggregate_component.is_approved</code>.
     */
    public void setIsApproved(Byte value) {
        set(7, value);
    }

    /**
     * Getter for
     * <code>oagi.specification_aggregate_component.is_approved</code>.
     */
    public Byte getIsApproved() {
        return (Byte) get(7);
    }

    /**
     * Setter for
     * <code>oagi.specification_aggregate_component.based_aggregate_component_id</code>.
     */
    public void setBasedAggregateComponentId(Long value) {
        set(8, value);
    }

    /**
     * Getter for
     * <code>oagi.specification_aggregate_component.based_aggregate_component_id</code>.
     */
    public Long getBasedAggregateComponentId() {
        return (Long) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SpecificationAggregateComponentRecord
     */
    public SpecificationAggregateComponentRecord() {
        super(SpecificationAggregateComponent.SPECIFICATION_AGGREGATE_COMPONENT);
    }

    /**
     * Create a detached, initialised SpecificationAggregateComponentRecord
     */
    public SpecificationAggregateComponentRecord(Long componentId, String definition, String componentName, Long specificationid, Long statusCodeId, Long gapAnalysisCodeId, ULong accId, Byte isApproved, Long basedAggregateComponentId) {
        super(SpecificationAggregateComponent.SPECIFICATION_AGGREGATE_COMPONENT);

        setComponentId(componentId);
        setDefinition(definition);
        setComponentName(componentName);
        setSpecificationid(specificationid);
        setStatusCodeId(statusCodeId);
        setGapAnalysisCodeId(gapAnalysisCodeId);
        setAccId(accId);
        setIsApproved(isApproved);
        setBasedAggregateComponentId(basedAggregateComponentId);
        resetChangedOnNotNull();
    }
}
