/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.repo.api.impl.jooq.entity.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.jooq.types.ULong;
import org.oagi.score.repo.api.impl.jooq.entity.tables.SpecificationBasicComponent;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpecificationBasicComponentRecord extends UpdatableRecordImpl<SpecificationBasicComponentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>oagi.specification_basic_component.component_id</code>.
     */
    public void setComponentId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>oagi.specification_basic_component.component_id</code>.
     */
    public Long getComponentId() {
        return (Long) get(0);
    }

    /**
     * Setter for
     * <code>oagi.specification_basic_component.component_name</code>.
     */
    public void setComponentName(String value) {
        set(1, value);
    }

    /**
     * Getter for
     * <code>oagi.specification_basic_component.component_name</code>.
     */
    public String getComponentName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>oagi.specification_basic_component.definition</code>.
     */
    public void setDefinition(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>oagi.specification_basic_component.definition</code>.
     */
    public String getDefinition() {
        return (String) get(2);
    }

    /**
     * Setter for
     * <code>oagi.specification_basic_component.min_cardinality</code>.
     */
    public void setMinCardinality(Integer value) {
        set(3, value);
    }

    /**
     * Getter for
     * <code>oagi.specification_basic_component.min_cardinality</code>.
     */
    public Integer getMinCardinality() {
        return (Integer) get(3);
    }

    /**
     * Setter for
     * <code>oagi.specification_basic_component.max_cardinality</code>.
     */
    public void setMaxCardinality(Integer value) {
        set(4, value);
    }

    /**
     * Getter for
     * <code>oagi.specification_basic_component.max_cardinality</code>.
     */
    public Integer getMaxCardinality() {
        return (Integer) get(4);
    }

    /**
     * Setter for
     * <code>oagi.specification_basic_component.value_constraint</code>.
     */
    public void setValueConstraint(String value) {
        set(5, value);
    }

    /**
     * Getter for
     * <code>oagi.specification_basic_component.value_constraint</code>.
     */
    public String getValueConstraint() {
        return (String) get(5);
    }

    /**
     * Setter for
     * <code>oagi.specification_basic_component.status_code_id</code>.
     */
    public void setStatusCodeId(Long value) {
        set(6, value);
    }

    /**
     * Getter for
     * <code>oagi.specification_basic_component.status_code_id</code>.
     */
    public Long getStatusCodeId() {
        return (Long) get(6);
    }

    /**
     * Setter for
     * <code>oagi.specification_basic_component.aggregate_component_id</code>.
     */
    public void setAggregateComponentId(Long value) {
        set(7, value);
    }

    /**
     * Getter for
     * <code>oagi.specification_basic_component.aggregate_component_id</code>.
     */
    public Long getAggregateComponentId() {
        return (Long) get(7);
    }

    /**
     * Setter for
     * <code>oagi.specification_basic_component.gap_analysis_code_id</code>.
     */
    public void setGapAnalysisCodeId(Long value) {
        set(8, value);
    }

    /**
     * Getter for
     * <code>oagi.specification_basic_component.gap_analysis_code_id</code>.
     */
    public Long getGapAnalysisCodeId() {
        return (Long) get(8);
    }

    /**
     * Setter for <code>oagi.specification_basic_component.bcc_id</code>.
     */
    public void setBccId(ULong value) {
        set(9, value);
    }

    /**
     * Getter for <code>oagi.specification_basic_component.bcc_id</code>.
     */
    public ULong getBccId() {
        return (ULong) get(9);
    }

    /**
     * Setter for <code>oagi.specification_basic_component.data_type_id</code>.
     */
    public void setDataTypeId(Long value) {
        set(10, value);
    }

    /**
     * Getter for <code>oagi.specification_basic_component.data_type_id</code>.
     */
    public Long getDataTypeId() {
        return (Long) get(10);
    }

    /**
     * Setter for <code>oagi.specification_basic_component.is_approved</code>.
     */
    public void setIsApproved(Byte value) {
        set(11, value);
    }

    /**
     * Getter for <code>oagi.specification_basic_component.is_approved</code>.
     */
    public Byte getIsApproved() {
        return (Byte) get(11);
    }

    /**
     * Setter for
     * <code>oagi.specification_basic_component.specification_id</code>.
     */
    public void setSpecificationId(Long value) {
        set(12, value);
    }

    /**
     * Getter for
     * <code>oagi.specification_basic_component.specification_id</code>.
     */
    public Long getSpecificationId() {
        return (Long) get(12);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SpecificationBasicComponentRecord
     */
    public SpecificationBasicComponentRecord() {
        super(SpecificationBasicComponent.SPECIFICATION_BASIC_COMPONENT);
    }

    /**
     * Create a detached, initialised SpecificationBasicComponentRecord
     */
    public SpecificationBasicComponentRecord(Long componentId, String componentName, String definition, Integer minCardinality, Integer maxCardinality, String valueConstraint, Long statusCodeId, Long aggregateComponentId, Long gapAnalysisCodeId, ULong bccId, Long dataTypeId, Byte isApproved, Long specificationId) {
        super(SpecificationBasicComponent.SPECIFICATION_BASIC_COMPONENT);

        setComponentId(componentId);
        setComponentName(componentName);
        setDefinition(definition);
        setMinCardinality(minCardinality);
        setMaxCardinality(maxCardinality);
        setValueConstraint(valueConstraint);
        setStatusCodeId(statusCodeId);
        setAggregateComponentId(aggregateComponentId);
        setGapAnalysisCodeId(gapAnalysisCodeId);
        setBccId(bccId);
        setDataTypeId(dataTypeId);
        setIsApproved(isApproved);
        setSpecificationId(specificationId);
        resetChangedOnNotNull();
    }
}
