/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.repo.api.impl.jooq.entity.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.oagi.score.repo.api.impl.jooq.entity.tables.SpecificationType;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpecificationTypeRecord extends UpdatableRecordImpl<SpecificationTypeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>oagi.specification_type.specification_type_id</code>.
     */
    public void setSpecificationTypeId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>oagi.specification_type.specification_type_id</code>.
     */
    public Long getSpecificationTypeId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>oagi.specification_type.specification_type_name</code>.
     */
    public void setSpecificationTypeName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>oagi.specification_type.specification_type_name</code>.
     */
    public String getSpecificationTypeName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SpecificationTypeRecord
     */
    public SpecificationTypeRecord() {
        super(SpecificationType.SPECIFICATION_TYPE);
    }

    /**
     * Create a detached, initialised SpecificationTypeRecord
     */
    public SpecificationTypeRecord(Long specificationTypeId, String specificationTypeName) {
        super(SpecificationType.SPECIFICATION_TYPE);

        setSpecificationTypeId(specificationTypeId);
        setSpecificationTypeName(specificationTypeName);
        resetChangedOnNotNull();
    }
}
