/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.repo.api.impl.jooq.entity.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.oagi.score.repo.api.impl.jooq.entity.tables.Specification;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpecificationRecord extends UpdatableRecordImpl<SpecificationRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>oagi.specification.specification_id</code>.
     */
    public void setSpecificationId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>oagi.specification.specification_id</code>.
     */
    public Long getSpecificationId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>oagi.specification.specification_type_id</code>.
     */
    public void setSpecificationTypeId(Long value) {
        set(1, value);
    }

    /**
     * Getter for <code>oagi.specification.specification_type_id</code>.
     */
    public Long getSpecificationTypeId() {
        return (Long) get(1);
    }

    /**
     * Setter for <code>oagi.specification.based_specification_id</code>.
     */
    public void setBasedSpecificationId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>oagi.specification.based_specification_id</code>.
     */
    public Long getBasedSpecificationId() {
        return (Long) get(2);
    }

    /**
     * Setter for <code>oagi.specification.source_id</code>.
     */
    public void setSourceId(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>oagi.specification.source_id</code>.
     */
    public Long getSourceId() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>oagi.specification.specification_name</code>.
     */
    public void setSpecificationName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>oagi.specification.specification_name</code>.
     */
    public String getSpecificationName() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SpecificationRecord
     */
    public SpecificationRecord() {
        super(Specification.SPECIFICATION);
    }

    /**
     * Create a detached, initialised SpecificationRecord
     */
    public SpecificationRecord(Long specificationId, Long specificationTypeId, Long basedSpecificationId, Long sourceId, String specificationName) {
        super(Specification.SPECIFICATION);

        setSpecificationId(specificationId);
        setSpecificationTypeId(specificationTypeId);
        setBasedSpecificationId(basedSpecificationId);
        setSourceId(sourceId);
        setSpecificationName(specificationName);
        resetChangedOnNotNull();
    }
}
