/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.repo.api.impl.jooq.entity.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.oagi.score.repo.api.impl.jooq.entity.tables.StatusCode;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class StatusCodeRecord extends UpdatableRecordImpl<StatusCodeRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>oagi.status_code.status_code_id</code>.
     */
    public void setStatusCodeId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>oagi.status_code.status_code_id</code>.
     */
    public Long getStatusCodeId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>oagi.status_code.code</code>.
     */
    public void setCode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>oagi.status_code.code</code>.
     */
    public String getCode() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached StatusCodeRecord
     */
    public StatusCodeRecord() {
        super(StatusCode.STATUS_CODE);
    }

    /**
     * Create a detached, initialised StatusCodeRecord
     */
    public StatusCodeRecord(Long statusCodeId, String code) {
        super(StatusCode.STATUS_CODE);

        setStatusCodeId(statusCodeId);
        setCode(code);
        resetChangedOnNotNull();
    }
}
