/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.repo.api.impl.jooq.entity.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.oagi.score.repo.api.impl.jooq.entity.tables.SuperAsccp;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SuperAsccpRecord extends UpdatableRecordImpl<SuperAsccpRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>oagi.super_asccp.super_asccp_id</code>.
     */
    public void setSuperAsccpId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>oagi.super_asccp.super_asccp_id</code>.
     */
    public Long getSuperAsccpId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>oagi.super_asccp.super_asccp_name</code>.
     */
    public void setSuperAsccpName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>oagi.super_asccp.super_asccp_name</code>.
     */
    public String getSuperAsccpName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>oagi.super_asccp.asccp_role_of_super_acc_id</code>.
     */
    public void setAsccpRoleOfSuperAccId(Long value) {
        set(2, value);
    }

    /**
     * Getter for <code>oagi.super_asccp.asccp_role_of_super_acc_id</code>.
     */
    public Long getAsccpRoleOfSuperAccId() {
        return (Long) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SuperAsccpRecord
     */
    public SuperAsccpRecord() {
        super(SuperAsccp.SUPER_ASCCP);
    }

    /**
     * Create a detached, initialised SuperAsccpRecord
     */
    public SuperAsccpRecord(Long superAsccpId, String superAsccpName, Long asccpRoleOfSuperAccId) {
        super(SuperAsccp.SUPER_ASCCP);

        setSuperAsccpId(superAsccpId);
        setSuperAsccpName(superAsccpName);
        setAsccpRoleOfSuperAccId(asccpRoleOfSuperAccId);
        resetChangedOnNotNull();
    }
}
