/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.repo.api.impl.jooq.entity.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.oagi.score.repo.api.impl.jooq.entity.tables.SuperAscc;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SuperAsccRecord extends UpdatableRecordImpl<SuperAsccRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>oagi.super_ascc.super_ascc_id</code>.
     */
    public void setSuperAsccId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>oagi.super_ascc.super_ascc_id</code>.
     */
    public Long getSuperAsccId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>oagi.super_ascc.super_ascc_name</code>.
     */
    public void setSuperAsccName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>oagi.super_ascc.super_ascc_name</code>.
     */
    public String getSuperAsccName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>oagi.super_ascc.min_cardinality</code>.
     */
    public void setMinCardinality(Integer value) {
        set(2, value);
    }

    /**
     * Getter for <code>oagi.super_ascc.min_cardinality</code>.
     */
    public Integer getMinCardinality() {
        return (Integer) get(2);
    }

    /**
     * Setter for <code>oagi.super_ascc.max_cardinality</code>.
     */
    public void setMaxCardinality(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>oagi.super_ascc.max_cardinality</code>.
     */
    public Integer getMaxCardinality() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>oagi.super_ascc.from_super_acc_id</code>.
     */
    public void setFromSuperAccId(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>oagi.super_ascc.from_super_acc_id</code>.
     */
    public Long getFromSuperAccId() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>oagi.super_ascc.super_asccp_id</code>.
     */
    public void setSuperAsccpId(Long value) {
        set(5, value);
    }

    /**
     * Getter for <code>oagi.super_ascc.super_asccp_id</code>.
     */
    public Long getSuperAsccpId() {
        return (Long) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SuperAsccRecord
     */
    public SuperAsccRecord() {
        super(SuperAscc.SUPER_ASCC);
    }

    /**
     * Create a detached, initialised SuperAsccRecord
     */
    public SuperAsccRecord(Long superAsccId, String superAsccName, Integer minCardinality, Integer maxCardinality, Long fromSuperAccId, Long superAsccpId) {
        super(SuperAscc.SUPER_ASCC);

        setSuperAsccId(superAsccId);
        setSuperAsccName(superAsccName);
        setMinCardinality(minCardinality);
        setMaxCardinality(maxCardinality);
        setFromSuperAccId(fromSuperAccId);
        setSuperAsccpId(superAsccpId);
        resetChangedOnNotNull();
    }
}
