/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.repo.api.impl.jooq.entity.tables.records;


import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;
import org.oagi.score.repo.api.impl.jooq.entity.tables.SuperBccp;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SuperBccpRecord extends UpdatableRecordImpl<SuperBccpRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>oagi.super_bccp.super_bccp_id</code>.
     */
    public void setSuperBccpId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>oagi.super_bccp.super_bccp_id</code>.
     */
    public Long getSuperBccpId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>oagi.super_bccp.super_bccp_name</code>.
     */
    public void setSuperBccpName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>oagi.super_bccp.super_bccp_name</code>.
     */
    public String getSuperBccpName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SuperBccpRecord
     */
    public SuperBccpRecord() {
        super(SuperBccp.SUPER_BCCP);
    }

    /**
     * Create a detached, initialised SuperBccpRecord
     */
    public SuperBccpRecord(Long superBccpId, String superBccpName) {
        super(SuperBccp.SUPER_BCCP);

        setSuperBccpId(superBccpId);
        setSuperBccpName(superBccpName);
        resetChangedOnNotNull();
    }
}
