/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.repo.api.impl.jooq.entity.tables;


import java.util.Collection;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.oagi.score.repo.api.impl.jooq.entity.Keys;
import org.oagi.score.repo.api.impl.jooq.entity.Oagi;
import org.oagi.score.repo.api.impl.jooq.entity.tables.BbieGapAnalysisResults.BbieGapAnalysisResultsPath;
import org.oagi.score.repo.api.impl.jooq.entity.tables.records.BieGapAnalysisConstraintsResultRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class BieGapAnalysisConstraintsResult extends TableImpl<BieGapAnalysisConstraintsResultRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>oagi.bie_gap_analysis_constraints_result</code>
     */
    public static final BieGapAnalysisConstraintsResult BIE_GAP_ANALYSIS_CONSTRAINTS_RESULT = new BieGapAnalysisConstraintsResult();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<BieGapAnalysisConstraintsResultRecord> getRecordType() {
        return BieGapAnalysisConstraintsResultRecord.class;
    }

    /**
     * The column
     * <code>oagi.bie_gap_analysis_constraints_result.result_id</code>.
     */
    public final TableField<BieGapAnalysisConstraintsResultRecord, Long> RESULT_ID = createField(DSL.name("result_id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column <code>oagi.bie_gap_analysis_constraints_result.code</code>.
     */
    public final TableField<BieGapAnalysisConstraintsResultRecord, String> CODE = createField(DSL.name("code"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    private BieGapAnalysisConstraintsResult(Name alias, Table<BieGapAnalysisConstraintsResultRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private BieGapAnalysisConstraintsResult(Name alias, Table<BieGapAnalysisConstraintsResultRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>oagi.bie_gap_analysis_constraints_result</code>
     * table reference
     */
    public BieGapAnalysisConstraintsResult(String alias) {
        this(DSL.name(alias), BIE_GAP_ANALYSIS_CONSTRAINTS_RESULT);
    }

    /**
     * Create an aliased <code>oagi.bie_gap_analysis_constraints_result</code>
     * table reference
     */
    public BieGapAnalysisConstraintsResult(Name alias) {
        this(alias, BIE_GAP_ANALYSIS_CONSTRAINTS_RESULT);
    }

    /**
     * Create a <code>oagi.bie_gap_analysis_constraints_result</code> table
     * reference
     */
    public BieGapAnalysisConstraintsResult() {
        this(DSL.name("bie_gap_analysis_constraints_result"), null);
    }

    public <O extends Record> BieGapAnalysisConstraintsResult(Table<O> path, ForeignKey<O, BieGapAnalysisConstraintsResultRecord> childPath, InverseForeignKey<O, BieGapAnalysisConstraintsResultRecord> parentPath) {
        super(path, childPath, parentPath, BIE_GAP_ANALYSIS_CONSTRAINTS_RESULT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class BieGapAnalysisConstraintsResultPath extends BieGapAnalysisConstraintsResult implements Path<BieGapAnalysisConstraintsResultRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> BieGapAnalysisConstraintsResultPath(Table<O> path, ForeignKey<O, BieGapAnalysisConstraintsResultRecord> childPath, InverseForeignKey<O, BieGapAnalysisConstraintsResultRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private BieGapAnalysisConstraintsResultPath(Name alias, Table<BieGapAnalysisConstraintsResultRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public BieGapAnalysisConstraintsResultPath as(String alias) {
            return new BieGapAnalysisConstraintsResultPath(DSL.name(alias), this);
        }

        @Override
        public BieGapAnalysisConstraintsResultPath as(Name alias) {
            return new BieGapAnalysisConstraintsResultPath(alias, this);
        }

        @Override
        public BieGapAnalysisConstraintsResultPath as(Table<?> alias) {
            return new BieGapAnalysisConstraintsResultPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Oagi.OAGI;
    }

    @Override
    public Identity<BieGapAnalysisConstraintsResultRecord, Long> getIdentity() {
        return (Identity<BieGapAnalysisConstraintsResultRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<BieGapAnalysisConstraintsResultRecord> getPrimaryKey() {
        return Keys.KEY_BIE_GAP_ANALYSIS_CONSTRAINTS_RESULT_PRIMARY;
    }

    private transient BbieGapAnalysisResultsPath _bbieGapAnalysisResults;

    /**
     * Get the implicit to-many join path to the
     * <code>oagi.bbie_gap_analysis_results</code> table
     */
    public BbieGapAnalysisResultsPath bbieGapAnalysisResults() {
        if (_bbieGapAnalysisResults == null)
            _bbieGapAnalysisResults = new BbieGapAnalysisResultsPath(this, null, Keys.FKBBIE_GAP_A910350.getInverseKey());

        return _bbieGapAnalysisResults;
    }

    @Override
    public BieGapAnalysisConstraintsResult as(String alias) {
        return new BieGapAnalysisConstraintsResult(DSL.name(alias), this);
    }

    @Override
    public BieGapAnalysisConstraintsResult as(Name alias) {
        return new BieGapAnalysisConstraintsResult(alias, this);
    }

    @Override
    public BieGapAnalysisConstraintsResult as(Table<?> alias) {
        return new BieGapAnalysisConstraintsResult(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public BieGapAnalysisConstraintsResult rename(String name) {
        return new BieGapAnalysisConstraintsResult(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public BieGapAnalysisConstraintsResult rename(Name name) {
        return new BieGapAnalysisConstraintsResult(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public BieGapAnalysisConstraintsResult rename(Table<?> name) {
        return new BieGapAnalysisConstraintsResult(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BieGapAnalysisConstraintsResult where(Condition condition) {
        return new BieGapAnalysisConstraintsResult(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BieGapAnalysisConstraintsResult where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BieGapAnalysisConstraintsResult where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BieGapAnalysisConstraintsResult where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BieGapAnalysisConstraintsResult where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BieGapAnalysisConstraintsResult where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BieGapAnalysisConstraintsResult where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public BieGapAnalysisConstraintsResult where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BieGapAnalysisConstraintsResult whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public BieGapAnalysisConstraintsResult whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
