/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.repo.api.impl.jooq.entity.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;
import org.oagi.score.repo.api.impl.jooq.entity.Indexes;
import org.oagi.score.repo.api.impl.jooq.entity.Keys;
import org.oagi.score.repo.api.impl.jooq.entity.Oagi;
import org.oagi.score.repo.api.impl.jooq.entity.tables.CcGapAnalysisResultCode.CcGapAnalysisResultCodePath;
import org.oagi.score.repo.api.impl.jooq.entity.tables.Specification.SpecificationPath;
import org.oagi.score.repo.api.impl.jooq.entity.tables.SpecificationAggregateComponent.SpecificationAggregateComponentPath;
import org.oagi.score.repo.api.impl.jooq.entity.tables.StatusCode.StatusCodePath;
import org.oagi.score.repo.api.impl.jooq.entity.tables.records.SpecificationAssociationComponentRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpecificationAssociationComponent extends TableImpl<SpecificationAssociationComponentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>oagi.specification_association_component</code>
     */
    public static final SpecificationAssociationComponent SPECIFICATION_ASSOCIATION_COMPONENT = new SpecificationAssociationComponent();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SpecificationAssociationComponentRecord> getRecordType() {
        return SpecificationAssociationComponentRecord.class;
    }

    /**
     * The column
     * <code>oagi.specification_association_component.component_id</code>.
     */
    public final TableField<SpecificationAssociationComponentRecord, Long> COMPONENT_ID = createField(DSL.name("component_id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column
     * <code>oagi.specification_association_component.association_name</code>.
     */
    public final TableField<SpecificationAssociationComponentRecord, String> ASSOCIATION_NAME = createField(DSL.name("association_name"), SQLDataType.VARCHAR(50).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column
     * <code>oagi.specification_association_component.definition</code>.
     */
    public final TableField<SpecificationAssociationComponentRecord, String> DEFINITION = createField(DSL.name("definition"), SQLDataType.VARCHAR(1500).defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.VARCHAR)), this, "");

    /**
     * The column
     * <code>oagi.specification_association_component.from_aggregate_component</code>.
     */
    public final TableField<SpecificationAssociationComponentRecord, Long> FROM_AGGREGATE_COMPONENT = createField(DSL.name("from_aggregate_component"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINT)), this, "");

    /**
     * The column
     * <code>oagi.specification_association_component.to_aggregate_component</code>.
     */
    public final TableField<SpecificationAssociationComponentRecord, Long> TO_AGGREGATE_COMPONENT = createField(DSL.name("to_aggregate_component"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column
     * <code>oagi.specification_association_component.gap_analysis_code_id</code>.
     */
    public final TableField<SpecificationAssociationComponentRecord, Long> GAP_ANALYSIS_CODE_ID = createField(DSL.name("gap_analysis_code_id"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINT)), this, "");

    /**
     * The column
     * <code>oagi.specification_association_component.status_code_id</code>.
     */
    public final TableField<SpecificationAssociationComponentRecord, Long> STATUS_CODE_ID = createField(DSL.name("status_code_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column
     * <code>oagi.specification_association_component.min_cardinality</code>.
     */
    public final TableField<SpecificationAssociationComponentRecord, Integer> MIN_CARDINALITY = createField(DSL.name("min_cardinality"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.INTEGER)), this, "");

    /**
     * The column
     * <code>oagi.specification_association_component.max_cardinality</code>.
     */
    public final TableField<SpecificationAssociationComponentRecord, Integer> MAX_CARDINALITY = createField(DSL.name("max_cardinality"), SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.INTEGER)), this, "");

    /**
     * The column <code>oagi.specification_association_component.ascc_id</code>.
     */
    public final TableField<SpecificationAssociationComponentRecord, ULong> ASCC_ID = createField(DSL.name("ascc_id"), SQLDataType.BIGINTUNSIGNED.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINTUNSIGNED)), this, "");

    /**
     * The column
     * <code>oagi.specification_association_component.is_approved</code>.
     */
    public final TableField<SpecificationAssociationComponentRecord, Byte> IS_APPROVED = createField(DSL.name("is_approved"), SQLDataType.TINYINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.TINYINT)), this, "");

    /**
     * The column
     * <code>oagi.specification_association_component.specification_id</code>.
     */
    public final TableField<SpecificationAssociationComponentRecord, Long> SPECIFICATION_ID = createField(DSL.name("specification_id"), SQLDataType.BIGINT.nullable(false), this, "");

    private SpecificationAssociationComponent(Name alias, Table<SpecificationAssociationComponentRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private SpecificationAssociationComponent(Name alias, Table<SpecificationAssociationComponentRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>oagi.specification_association_component</code>
     * table reference
     */
    public SpecificationAssociationComponent(String alias) {
        this(DSL.name(alias), SPECIFICATION_ASSOCIATION_COMPONENT);
    }

    /**
     * Create an aliased <code>oagi.specification_association_component</code>
     * table reference
     */
    public SpecificationAssociationComponent(Name alias) {
        this(alias, SPECIFICATION_ASSOCIATION_COMPONENT);
    }

    /**
     * Create a <code>oagi.specification_association_component</code> table
     * reference
     */
    public SpecificationAssociationComponent() {
        this(DSL.name("specification_association_component"), null);
    }

    public <O extends Record> SpecificationAssociationComponent(Table<O> path, ForeignKey<O, SpecificationAssociationComponentRecord> childPath, InverseForeignKey<O, SpecificationAssociationComponentRecord> parentPath) {
        super(path, childPath, parentPath, SPECIFICATION_ASSOCIATION_COMPONENT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SpecificationAssociationComponentPath extends SpecificationAssociationComponent implements Path<SpecificationAssociationComponentRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SpecificationAssociationComponentPath(Table<O> path, ForeignKey<O, SpecificationAssociationComponentRecord> childPath, InverseForeignKey<O, SpecificationAssociationComponentRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SpecificationAssociationComponentPath(Name alias, Table<SpecificationAssociationComponentRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SpecificationAssociationComponentPath as(String alias) {
            return new SpecificationAssociationComponentPath(DSL.name(alias), this);
        }

        @Override
        public SpecificationAssociationComponentPath as(Name alias) {
            return new SpecificationAssociationComponentPath(alias, this);
        }

        @Override
        public SpecificationAssociationComponentPath as(Table<?> alias) {
            return new SpecificationAssociationComponentPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Oagi.OAGI;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.SPECIFICATION_ASSOCIATION_COMPONENT_FKSPECIFICAT961521_IDX);
    }

    @Override
    public Identity<SpecificationAssociationComponentRecord, Long> getIdentity() {
        return (Identity<SpecificationAssociationComponentRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<SpecificationAssociationComponentRecord> getPrimaryKey() {
        return Keys.KEY_SPECIFICATION_ASSOCIATION_COMPONENT_PRIMARY;
    }

    @Override
    public List<ForeignKey<SpecificationAssociationComponentRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FKSPECIFICAT961520, Keys.FKSPECIFICAT113911, Keys.FKSPECIFICAT801095, Keys.FKSPECIFICAT203312, Keys.FKSPECIFICAT293179);
    }

    private transient SpecificationAggregateComponentPath _fkspecificat961520;

    /**
     * Get the implicit join path to the
     * <code>oagi.specification_aggregate_component</code> table, via the
     * <code>FKspecificat961520</code> key.
     */
    public SpecificationAggregateComponentPath fkspecificat961520() {
        if (_fkspecificat961520 == null)
            _fkspecificat961520 = new SpecificationAggregateComponentPath(this, Keys.FKSPECIFICAT961520, null);

        return _fkspecificat961520;
    }

    private transient SpecificationAggregateComponentPath _fkspecificat113911;

    /**
     * Get the implicit join path to the
     * <code>oagi.specification_aggregate_component</code> table, via the
     * <code>FKspecificat113911</code> key.
     */
    public SpecificationAggregateComponentPath fkspecificat113911() {
        if (_fkspecificat113911 == null)
            _fkspecificat113911 = new SpecificationAggregateComponentPath(this, Keys.FKSPECIFICAT113911, null);

        return _fkspecificat113911;
    }

    private transient CcGapAnalysisResultCodePath _ccGapAnalysisResultCode;

    /**
     * Get the implicit join path to the
     * <code>oagi.cc_gap_analysis_result_code</code> table.
     */
    public CcGapAnalysisResultCodePath ccGapAnalysisResultCode() {
        if (_ccGapAnalysisResultCode == null)
            _ccGapAnalysisResultCode = new CcGapAnalysisResultCodePath(this, Keys.FKSPECIFICAT801095, null);

        return _ccGapAnalysisResultCode;
    }

    private transient StatusCodePath _statusCode;

    /**
     * Get the implicit join path to the <code>oagi.status_code</code> table.
     */
    public StatusCodePath statusCode() {
        if (_statusCode == null)
            _statusCode = new StatusCodePath(this, Keys.FKSPECIFICAT203312, null);

        return _statusCode;
    }

    private transient SpecificationPath _specification;

    /**
     * Get the implicit join path to the <code>oagi.specification</code> table.
     */
    public SpecificationPath specification() {
        if (_specification == null)
            _specification = new SpecificationPath(this, Keys.FKSPECIFICAT293179, null);

        return _specification;
    }

    @Override
    public SpecificationAssociationComponent as(String alias) {
        return new SpecificationAssociationComponent(DSL.name(alias), this);
    }

    @Override
    public SpecificationAssociationComponent as(Name alias) {
        return new SpecificationAssociationComponent(alias, this);
    }

    @Override
    public SpecificationAssociationComponent as(Table<?> alias) {
        return new SpecificationAssociationComponent(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SpecificationAssociationComponent rename(String name) {
        return new SpecificationAssociationComponent(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SpecificationAssociationComponent rename(Name name) {
        return new SpecificationAssociationComponent(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SpecificationAssociationComponent rename(Table<?> name) {
        return new SpecificationAssociationComponent(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SpecificationAssociationComponent where(Condition condition) {
        return new SpecificationAssociationComponent(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SpecificationAssociationComponent where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SpecificationAssociationComponent where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SpecificationAssociationComponent where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SpecificationAssociationComponent where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SpecificationAssociationComponent where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SpecificationAssociationComponent where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SpecificationAssociationComponent where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SpecificationAssociationComponent whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SpecificationAssociationComponent whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
