/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.repo.api.impl.jooq.entity.tables;


import java.util.Arrays;
import java.util.Collection;
import java.util.List;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.InverseForeignKey;
import org.jooq.Name;
import org.jooq.Path;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.Record;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;
import org.jooq.types.ULong;
import org.oagi.score.repo.api.impl.jooq.entity.Indexes;
import org.oagi.score.repo.api.impl.jooq.entity.Keys;
import org.oagi.score.repo.api.impl.jooq.entity.Oagi;
import org.oagi.score.repo.api.impl.jooq.entity.tables.Acc.AccPath;
import org.oagi.score.repo.api.impl.jooq.entity.tables.CcGapAnalysisResultCode.CcGapAnalysisResultCodePath;
import org.oagi.score.repo.api.impl.jooq.entity.tables.Specification.SpecificationPath;
import org.oagi.score.repo.api.impl.jooq.entity.tables.SpecificationAggregateComponent.SpecificationAggregateComponentPath;
import org.oagi.score.repo.api.impl.jooq.entity.tables.SpecificationAssociationComponent.SpecificationAssociationComponentPath;
import org.oagi.score.repo.api.impl.jooq.entity.tables.SpecificationBasicComponent.SpecificationBasicComponentPath;
import org.oagi.score.repo.api.impl.jooq.entity.tables.StatusCode.StatusCodePath;
import org.oagi.score.repo.api.impl.jooq.entity.tables.records.SpecificationAggregateComponentRecord;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SpecificationAggregateComponent extends TableImpl<SpecificationAggregateComponentRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of
     * <code>oagi.specification_aggregate_component</code>
     */
    public static final SpecificationAggregateComponent SPECIFICATION_AGGREGATE_COMPONENT = new SpecificationAggregateComponent();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<SpecificationAggregateComponentRecord> getRecordType() {
        return SpecificationAggregateComponentRecord.class;
    }

    /**
     * The column
     * <code>oagi.specification_aggregate_component.component_id</code>.
     */
    public final TableField<SpecificationAggregateComponentRecord, Long> COMPONENT_ID = createField(DSL.name("component_id"), SQLDataType.BIGINT.nullable(false).identity(true), this, "");

    /**
     * The column
     * <code>oagi.specification_aggregate_component.definition</code>.
     */
    public final TableField<SpecificationAggregateComponentRecord, String> DEFINITION = createField(DSL.name("definition"), SQLDataType.VARCHAR(500).nullable(false), this, "");

    /**
     * The column
     * <code>oagi.specification_aggregate_component.component_name</code>.
     */
    public final TableField<SpecificationAggregateComponentRecord, String> COMPONENT_NAME = createField(DSL.name("component_name"), SQLDataType.VARCHAR(50).nullable(false), this, "");

    /**
     * The column
     * <code>oagi.specification_aggregate_component.specificationid</code>.
     */
    public final TableField<SpecificationAggregateComponentRecord, Long> SPECIFICATIONID = createField(DSL.name("specificationid"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column
     * <code>oagi.specification_aggregate_component.status_code_id</code>.
     */
    public final TableField<SpecificationAggregateComponentRecord, Long> STATUS_CODE_ID = createField(DSL.name("status_code_id"), SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column
     * <code>oagi.specification_aggregate_component.gap_analysis_code_id</code>.
     */
    public final TableField<SpecificationAggregateComponentRecord, Long> GAP_ANALYSIS_CODE_ID = createField(DSL.name("gap_analysis_code_id"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINT)), this, "");

    /**
     * The column <code>oagi.specification_aggregate_component.acc_id</code>.
     */
    public final TableField<SpecificationAggregateComponentRecord, ULong> ACC_ID = createField(DSL.name("acc_id"), SQLDataType.BIGINTUNSIGNED.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINTUNSIGNED)), this, "");

    /**
     * The column
     * <code>oagi.specification_aggregate_component.is_approved</code>.
     */
    public final TableField<SpecificationAggregateComponentRecord, Byte> IS_APPROVED = createField(DSL.name("is_approved"), SQLDataType.TINYINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.TINYINT)), this, "");

    /**
     * The column
     * <code>oagi.specification_aggregate_component.based_aggregate_component_id</code>.
     */
    public final TableField<SpecificationAggregateComponentRecord, Long> BASED_AGGREGATE_COMPONENT_ID = createField(DSL.name("based_aggregate_component_id"), SQLDataType.BIGINT.defaultValue(DSL.field(DSL.raw("NULL"), SQLDataType.BIGINT)), this, "");

    private SpecificationAggregateComponent(Name alias, Table<SpecificationAggregateComponentRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private SpecificationAggregateComponent(Name alias, Table<SpecificationAggregateComponentRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>oagi.specification_aggregate_component</code>
     * table reference
     */
    public SpecificationAggregateComponent(String alias) {
        this(DSL.name(alias), SPECIFICATION_AGGREGATE_COMPONENT);
    }

    /**
     * Create an aliased <code>oagi.specification_aggregate_component</code>
     * table reference
     */
    public SpecificationAggregateComponent(Name alias) {
        this(alias, SPECIFICATION_AGGREGATE_COMPONENT);
    }

    /**
     * Create a <code>oagi.specification_aggregate_component</code> table
     * reference
     */
    public SpecificationAggregateComponent() {
        this(DSL.name("specification_aggregate_component"), null);
    }

    public <O extends Record> SpecificationAggregateComponent(Table<O> path, ForeignKey<O, SpecificationAggregateComponentRecord> childPath, InverseForeignKey<O, SpecificationAggregateComponentRecord> parentPath) {
        super(path, childPath, parentPath, SPECIFICATION_AGGREGATE_COMPONENT);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class SpecificationAggregateComponentPath extends SpecificationAggregateComponent implements Path<SpecificationAggregateComponentRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> SpecificationAggregateComponentPath(Table<O> path, ForeignKey<O, SpecificationAggregateComponentRecord> childPath, InverseForeignKey<O, SpecificationAggregateComponentRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private SpecificationAggregateComponentPath(Name alias, Table<SpecificationAggregateComponentRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public SpecificationAggregateComponentPath as(String alias) {
            return new SpecificationAggregateComponentPath(DSL.name(alias), this);
        }

        @Override
        public SpecificationAggregateComponentPath as(Name alias) {
            return new SpecificationAggregateComponentPath(alias, this);
        }

        @Override
        public SpecificationAggregateComponentPath as(Table<?> alias) {
            return new SpecificationAggregateComponentPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Oagi.OAGI;
    }

    @Override
    public List<Index> getIndexes() {
        return Arrays.asList(Indexes.SPECIFICATION_AGGREGATE_COMPONENT_GFGDFGDFG_IDX);
    }

    @Override
    public Identity<SpecificationAggregateComponentRecord, Long> getIdentity() {
        return (Identity<SpecificationAggregateComponentRecord, Long>) super.getIdentity();
    }

    @Override
    public UniqueKey<SpecificationAggregateComponentRecord> getPrimaryKey() {
        return Keys.KEY_SPECIFICATION_AGGREGATE_COMPONENT_PRIMARY;
    }

    @Override
    public List<ForeignKey<SpecificationAggregateComponentRecord, ?>> getReferences() {
        return Arrays.asList(Keys.FKSPECIFICAT261745, Keys.FKSPECIFICAT466081, Keys.FKSPECIFICAT868297, Keys.GFGDFGDFG, Keys.FKSPECIFICAT225174);
    }

    private transient SpecificationPath _specification;

    /**
     * Get the implicit join path to the <code>oagi.specification</code> table.
     */
    public SpecificationPath specification() {
        if (_specification == null)
            _specification = new SpecificationPath(this, Keys.FKSPECIFICAT261745, null);

        return _specification;
    }

    private transient StatusCodePath _statusCode;

    /**
     * Get the implicit join path to the <code>oagi.status_code</code> table.
     */
    public StatusCodePath statusCode() {
        if (_statusCode == null)
            _statusCode = new StatusCodePath(this, Keys.FKSPECIFICAT466081, null);

        return _statusCode;
    }

    private transient CcGapAnalysisResultCodePath _ccGapAnalysisResultCode;

    /**
     * Get the implicit join path to the
     * <code>oagi.cc_gap_analysis_result_code</code> table.
     */
    public CcGapAnalysisResultCodePath ccGapAnalysisResultCode() {
        if (_ccGapAnalysisResultCode == null)
            _ccGapAnalysisResultCode = new CcGapAnalysisResultCodePath(this, Keys.FKSPECIFICAT868297, null);

        return _ccGapAnalysisResultCode;
    }

    private transient AccPath _acc;

    /**
     * Get the implicit join path to the <code>oagi.acc</code> table.
     */
    public AccPath acc() {
        if (_acc == null)
            _acc = new AccPath(this, Keys.GFGDFGDFG, null);

        return _acc;
    }

    private transient SpecificationAggregateComponentPath _specificationAggregateComponent;

    /**
     * Get the implicit join path to the
     * <code>oagi.specification_aggregate_component</code> table.
     */
    public SpecificationAggregateComponentPath specificationAggregateComponent() {
        if (_specificationAggregateComponent == null)
            _specificationAggregateComponent = new SpecificationAggregateComponentPath(this, Keys.FKSPECIFICAT225174, null);

        return _specificationAggregateComponent;
    }

    private transient SpecificationAssociationComponentPath _fkspecificat113911;

    /**
     * Get the implicit to-many join path to the
     * <code>oagi.specification_association_component</code> table, via the
     * <code>FKspecificat113911</code> key
     */
    public SpecificationAssociationComponentPath fkspecificat113911() {
        if (_fkspecificat113911 == null)
            _fkspecificat113911 = new SpecificationAssociationComponentPath(this, null, Keys.FKSPECIFICAT113911.getInverseKey());

        return _fkspecificat113911;
    }

    private transient SpecificationBasicComponentPath _specificationBasicComponent;

    /**
     * Get the implicit to-many join path to the
     * <code>oagi.specification_basic_component</code> table
     */
    public SpecificationBasicComponentPath specificationBasicComponent() {
        if (_specificationBasicComponent == null)
            _specificationBasicComponent = new SpecificationBasicComponentPath(this, null, Keys.FKSPECIFICAT950731.getInverseKey());

        return _specificationBasicComponent;
    }

    private transient SpecificationAssociationComponentPath _fkspecificat961520;

    /**
     * Get the implicit to-many join path to the
     * <code>oagi.specification_association_component</code> table, via the
     * <code>FKspecificat961520</code> key
     */
    public SpecificationAssociationComponentPath fkspecificat961520() {
        if (_fkspecificat961520 == null)
            _fkspecificat961520 = new SpecificationAssociationComponentPath(this, null, Keys.FKSPECIFICAT961520.getInverseKey());

        return _fkspecificat961520;
    }

    @Override
    public SpecificationAggregateComponent as(String alias) {
        return new SpecificationAggregateComponent(DSL.name(alias), this);
    }

    @Override
    public SpecificationAggregateComponent as(Name alias) {
        return new SpecificationAggregateComponent(alias, this);
    }

    @Override
    public SpecificationAggregateComponent as(Table<?> alias) {
        return new SpecificationAggregateComponent(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public SpecificationAggregateComponent rename(String name) {
        return new SpecificationAggregateComponent(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public SpecificationAggregateComponent rename(Name name) {
        return new SpecificationAggregateComponent(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public SpecificationAggregateComponent rename(Table<?> name) {
        return new SpecificationAggregateComponent(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SpecificationAggregateComponent where(Condition condition) {
        return new SpecificationAggregateComponent(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SpecificationAggregateComponent where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SpecificationAggregateComponent where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SpecificationAggregateComponent where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SpecificationAggregateComponent where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SpecificationAggregateComponent where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SpecificationAggregateComponent where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public SpecificationAggregateComponent where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SpecificationAggregateComponent whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public SpecificationAggregateComponent whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
