/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.repo.api.impl.jooq.entity.routines;


import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.oagi.score.repo.api.impl.jooq.entity.Oagi;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class FillTheFlatBccTable extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>oagi.fill_the_flat_bcc_table.initialACC</code>.
     */
    public static final Parameter<Integer> INITIALACC = Internal.createParameter("initialACC", SQLDataType.INTEGER, false, false);

    /**
     * Create a new routine call instance
     */
    public FillTheFlatBccTable() {
        super("fill_the_flat_bcc_table", Oagi.OAGI);

        addInParameter(INITIALACC);
    }

    /**
     * Set the <code>initialACC</code> parameter IN value to the routine
     */
    public void setInitialacc(Integer value) {
        setValue(INITIALACC, value);
    }
}
