/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.repo.api.impl.jooq.entity.routines;


import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.oagi.score.repo.api.impl.jooq.entity.Oagi;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GetAllRelatedAccs extends AbstractRoutine<Long> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter <code>oagi.get_all_related_ACCs.RETURN_VALUE</code>.
     */
    public static final Parameter<Long> RETURN_VALUE = Internal.createParameter("RETURN_VALUE", SQLDataType.BIGINT, false, false);

    /**
     * The parameter <code>oagi.get_all_related_ACCs.accID</code>.
     */
    public static final Parameter<Long> ACCID = Internal.createParameter("accID", SQLDataType.BIGINT, false, false);

    /**
     * Create a new routine call instance
     */
    public GetAllRelatedAccs() {
        super("get_all_related_ACCs", Oagi.OAGI, SQLDataType.BIGINT);

        setReturnParameter(RETURN_VALUE);
        addInParameter(ACCID);
    }

    /**
     * Set the <code>accID</code> parameter IN value to the routine
     */
    public void setAccid(Long value) {
        setValue(ACCID, value);
    }

    /**
     * Set the <code>accID</code> parameter to the function to be used with a
     * {@link org.jooq.Select} statement
     */
    public void setAccid(Field<Long> field) {
        setField(ACCID, field);
    }
}
