/*
 * This file is generated by jOOQ.
 */
package org.oagi.score.repo.api.impl.jooq.entity.routines;


import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.oagi.score.repo.api.impl.jooq.entity.Oagi;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProcessBccListFromBased extends AbstractRoutine<java.lang.Void> {

    private static final long serialVersionUID = 1L;

    /**
     * The parameter
     * <code>oagi.process_bcc_list_from_based.originalACCManifestID</code>.
     */
    public static final Parameter<Integer> ORIGINALACCMANIFESTID = Internal.createParameter("originalACCManifestID", SQLDataType.INTEGER, false, false);

    /**
     * The parameter
     * <code>oagi.process_bcc_list_from_based.basedACCManinfestID</code>.
     */
    public static final Parameter<Integer> BASEDACCMANINFESTID = Internal.createParameter("basedACCManinfestID", SQLDataType.INTEGER, false, false);

    /**
     * The parameter <code>oagi.process_bcc_list_from_based.path</code>.
     */
    public static final Parameter<byte[]> PATH = Internal.createParameter("path", SQLDataType.BLOB, false, false);

    /**
     * Create a new routine call instance
     */
    public ProcessBccListFromBased() {
        super("process_bcc_list_from_based", Oagi.OAGI);

        addInParameter(ORIGINALACCMANIFESTID);
        addInParameter(BASEDACCMANINFESTID);
        addInParameter(PATH);
    }

    /**
     * Set the <code>originalACCManifestID</code> parameter IN value to the
     * routine
     */
    public void setOriginalaccmanifestid(Integer value) {
        setValue(ORIGINALACCMANIFESTID, value);
    }

    /**
     * Set the <code>basedACCManinfestID</code> parameter IN value to the
     * routine
     */
    public void setBasedaccmaninfestid(Integer value) {
        setValue(BASEDACCMANINFESTID, value);
    }

    /**
     * Set the <code>path</code> parameter IN value to the routine
     */
    public void setPath(byte[] value) {
        setValue(PATH, value);
    }
}
